version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws-staging"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
confirm_changeset = false
resolve_s3 = true
fail_on_empty_changeset = false
